-- =============================================
-- Customer Segmentation & Analysis Report
-- =============================================
-- Description: Creates a comprehensive customer analysis view with segmentation,
--              RFM metrics, and customer lifetime value calculations
-- Business Value: Identifies VIP customers, tracks customer behavior patterns,
--                 and enables targeted marketing strategies
-- Author: [Murali Jami]
-- Date: October 2025
-- =============================================

CREATE VIEW gold_customer_report AS 

-- Step 1: Base Query - Join customer and sales data

WITH base_query AS (
    SELECT 
        f.order_number, 
        f.product_key, 
        f.order_date,
        f.sales_amount,
        f.quantity,
        f.price, 
        c.customer_key, 
        c.customer_number,
        CONCAT(c.first_name, ' ', c.last_name) AS full_name,
        -- Calculate customer age from birthdate
        COALESCE(TIMESTAMPDIFF(YEAR, c.birthdate, CURRENT_DATE()), 0) AS age
    FROM gold_fact_sales f 
    LEFT JOIN gold_dim_customers c 
        ON c.customer_key = f.customer_key
    WHERE f.order_date IS NOT NULL
),

-- Step 2: Customer Aggregation - Calculate key metrics per customer

customer_aggregation AS (
    SELECT 
        customer_key, 
        customer_number,
        full_name, 
        age, 
        -- Total number of unique orders
        COUNT(DISTINCT order_number) AS total_orders,
        -- Total revenue generated by customer
        SUM(sales_amount) AS total_sales,
        -- Total items purchased
        SUM(quantity) AS total_quantity,
        -- Number of unique products purchased
        COUNT(DISTINCT product_key) AS total_products,
        -- Most recent purchase date
        MAX(order_date) AS last_order_date,
        -- Customer lifespan in months (first to last order)
        COALESCE(TIMESTAMPDIFF(MONTH, MIN(order_date), MAX(order_date)), 0) AS lifespan
    FROM base_query
    GROUP BY customer_key, customer_number, full_name, age
)

-- Step 3: Final Report - Add segmentation and calculated metrics

SELECT 
    customer_key, 
    customer_number,
    full_name, 
    age,
    
    -- Age-based segmentation for demographic targeting
    CASE 
        WHEN age < 20 THEN "Under 20"
        WHEN age BETWEEN 20 AND 29 THEN "20-29"
        WHEN age BETWEEN 30 AND 39 THEN "30-39"
        WHEN age BETWEEN 40 AND 49 THEN "40-49"
        ELSE "50 and above" 
    END AS age_group,
    
    -- Customer value segmentation based on spend and loyalty
    -- VIP: High spenders with 12+ months relationship
    -- Regular: Moderate spenders with 12+ months relationship  
    -- New: Customers with less than 12 months relationship
    CASE 
        WHEN total_sales > 5000 AND lifespan >= 12 THEN "VIP"
        WHEN total_sales <= 5000 AND lifespan >= 12 THEN "Regular"
        ELSE "New" 
    END AS customer_segment,
    
    -- RFM Analysis Metrics
    -- Recency: Months since last order (lower = better)
    TIMESTAMPDIFF(MONTH, last_order_date, CURRENT_DATE()) AS recency,
    
    -- Average order value
    ROUND(total_sales / NULLIF(total_orders, 0)) AS avg_order_value,
    
    -- Average monthly spending
    ROUND(total_sales / NULLIF(lifespan, 0)) AS avg_monthly_spend,
    
    -- Core metrics
    total_orders,
    total_sales,
    total_quantity,
    total_products,
    last_order_date,
    lifespan
FROM customer_aggregation
ORDER BY total_sales DESC;

-- =============================================
-- Sample Usage:
-- SELECT * FROM gold_customer_report WHERE customer_segment = 'VIP';
-- SELECT age_group, COUNT(*) FROM gold_customer_report GROUP BY age_group;
-- =============================================
